services:
  backend:
    build: .
    ports:
      - "8000:8000"
      - "50051:50051"
    networks:
      - poc-network

  test-rest:
    build: .
    command: python test_rest.py
    environment:
      - SERVER_HOST=backend
    depends_on:
      - backend
    networks:
      - poc-network

  test-grpc:
    build: .
    command: python test_client.py
    environment:
      - SERVER_HOST=backend
    depends_on:
      - backend
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
