# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/schema.proto\x12\x08poc_grpc\"\x1c\n\x0b\x44\x61taRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"4\n\x0c\x44\x61taResponse\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x15.poc_grpc.UserProfile\"\xee\x02\n\x0bUserProfile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x0b\n\x03\x62io\x18\x06 \x01(\t\x12\"\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x11.poc_grpc.Address\x12\x32\n\x0ctransactions\x18\x08 \x03(\x0b\x32\x1c.poc_grpc.TransactionHistory\x12\x35\n\x08metadata\x18\t \x03(\x0b\x32#.poc_grpc.UserProfile.MetadataEntry\x12\x11\n\tis_active\x18\n \x01(\x08\x12\x18\n\x10reputation_score\x18\x0b \x01(\x01\x12\x11\n\tjoined_at\x18\x0c \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x10\n\x08zip_code\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12$\n\x08location\x18\x06 \x01(\x0b\x32\x12.poc_grpc.Location\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x94\x01\n\x12TransactionHistory\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0c\n\x04tags\x18\x07 \x03(\t2L\n\x0b\x44\x61taService\x12=\n\x0cGetHeavyData\x12\x15.poc_grpc.DataRequest\x1a\x16.poc_grpc.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPROFILE_METADATAENTRY']._loaded_options = None
  _globals['_USERPROFILE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DATAREQUEST']._serialized_start=33
  _globals['_DATAREQUEST']._serialized_end=61
  _globals['_DATARESPONSE']._serialized_start=63
  _globals['_DATARESPONSE']._serialized_end=115
  _globals['_USERPROFILE']._serialized_start=118
  _globals['_USERPROFILE']._serialized_end=484
  _globals['_USERPROFILE_METADATAENTRY']._serialized_start=437
  _globals['_USERPROFILE_METADATAENTRY']._serialized_end=484
  _globals['_ADDRESS']._serialized_start=486
  _globals['_ADDRESS']._serialized_end=613
  _globals['_LOCATION']._serialized_start=615
  _globals['_LOCATION']._serialized_end=662
  _globals['_TRANSACTIONHISTORY']._serialized_start=665
  _globals['_TRANSACTIONHISTORY']._serialized_end=813
  _globals['_DATASERVICE']._serialized_start=815
  _globals['_DATASERVICE']._serialized_end=891
# @@protoc_insertion_point(module_scope)
